project:
  type: website

website:
  # navbar supprimÃ©e Ã  la demande de l'utilisateur

  page-footer:
    center: "Â© 2025 CFI â€“ Tous droits rÃ©servÃ©s"
format:
  html:
    theme: flatly               # thÃ¨me bootswatch
    css:
      - styles.css          # Chemin relatif depuis  vers la racine
    fig-align: center
    toc: true
    toc-location: left
    toc-title: "Table des matiÃ¨res"  # ğŸ‘ˆ Titre personnalisÃ©# Pour bien positionner la TOC Ã  gauche
    toc-depth: 2                 # Ajuste la profondeur de la TOC selon tes titres
    number-sections: true
    self-contained: true

output-dir: _site                # GÃ©nÃ¨re directement dans _site/ (pas _site/)

execute:
  echo: true                    # (optionnel) affiche le code exÃ©cutÃ© dans les .qmd

