project:
  type: website

website:
  navbar:
    background: success   # Vert for√™t
    foreground: white
    left:
      - text: "<i class='bi bi-hospital'></i> RAPPOR PTME"
        href: tracking-ptme.qmd
      - text: "<i class='bi bi-flower3'></i> RAPPORT JARDINAGE"
        href: tracking-gardening.qmd
      - text: "<i class='bi bi-people'></i> RAPPORT OEV"
        href: tracking-oev.qmd
      - text: "<i class='bi bi-bar-chart-line'></i> RAPPORT MUSO"
        href: tracking-muso.qmd
      - text: "<i class='bi bi-egg-fried'></i> RAPPORT NUTRITION"
        href: tracking-nutrition.qmd
      - text: "<i class='bi bi-telephone'></i> RAPPORT VISITES ET APPELS"
        href: tracking-call.qmd

  page-footer:
    center: "¬© 2025 CFI ‚Äì Tous droits r√©serv√©s"
format:
  html:
    theme: flatly               # th√®me bootswatch
    css:
      - styles.css          # Chemin relatif depuis  vers la racine
    fig-align: center
    toc: true
    toc-location: left
    toc-title: "Table des mati√®res"  # üëà Titre personnalis√©# Pour bien positionner la TOC √† gauche
    toc-depth: 2                 # Ajuste la profondeur de la TOC selon tes titres
    number-sections: true
    self-contained: true

output-dir: _site                # G√©n√®re directement dans _site/ (pas _site/)

execute:
  echo: true                    # (optionnel) affiche le code ex√©cut√© dans les .qmd

